const cors = require("cors");
const express = require("express");
const routes = require("./routes");
const app = express();
app.use(cors()); app.use(express.json());
app.get("/health", (_, res) => res.json({ service: "notification", status: "ok" }));
app.use("/notifications", routes);
app.use((req, res) => res.status(404).json({ error: "Not found" }));
app.use((err, req, res, next) => { console.error(err.stack); res.status(500).json({ error: "Internal server error" }); });
module.exports = app;
